[tools]
bat = "latest"
lsd = "latest"
ripgrep = "latest"
fd = "latest"
node = "25"
python = "3.12"
go = "1.25"
lua = "latest"
neovim = "0.11.5"
starship = "latest"
tree-sitter = "0.25.10"
uv = "latest"
atuin = "latest"
yazi = "25.5.31"
